### ISSUE TITLE
System.Runtime.InteropServices.COMException:“没有注册类 (0x80040154 (REGDB_E_CLASSNOTREG))”

### ISSUE THREAD

**Issue by Ming-jiayou** [JamesnetGroup/leagueoflegends-winui3#1]
运行报错System.Runtime.InteropServices.COMException:“没有注册类 (0x80040154 (REGDB_E_CLASSNOTREG))”
![image](https://github.com/user-attachments/assets/ef6b7b6b-77f7-4a83-ba08-b467b1959e7a)

**Comment by vickyqu115** [comment]
可能是 SDK 没有正确安装的可能性比较大。
你可以在 Visual Studio Installer 中安装一下和 WinUI3 相关的安装项目，然后重新启动 Visual Studio 试试看！
有问题再反馈给我～

**Comment by jamesnet214** [comment]
@Ming-jiayou  it's possible that the WinUI 3-related SDK is not properly installed. Could you check and compare it?"

![image](https://github.com/user-attachments/assets/73e2c1dc-36a1-4b6c-b67f-30f88fdafdf5)

**Comment by Ming-jiayou** [comment]
Thank you for your reply. I seem to have installed the relevant SDK.
![image](https://github.com/user-attachments/assets/6ccd5e5f-92c0-4d04-b751-577ca9ed298d)

**Comment by Ming-jiayou** [comment]
Thank you for your efforts. I will learn the WPF version and the Uno version. If many people encounter this issue, you can address it later.
